python xifaims_analysis.py parameters/faims_minimal.yaml data/4PM_DSS_LS_nonunique1pCSM.csv
python xifaims_analysis.py parameters/faims_smaller.yaml data/4PM_DSS_LS_nonunique1pCSM.csv
python xifaims_analysis.py parameters/faims_small.yaml data/4PM_DSS_LS_nonunique1pCSM.csv
python xifaims_analysis.py parameters/faims_structure.yaml data/4PM_DSS_LS_nonunique1pCSM.csv
python xifaims_analysis.py parameters/faims_all.yaml data/4PM_DSS_LS_nonunique1pCSM.csv



python xifaims_analysis.py parameters/faims_minimal.yaml data/combined_8PMLunique_4PMLS_nonu.csv
python xifaims_analysis.py parameters/faims_smaller.yaml data/combined_8PMLunique_4PMLS_nonu.csv
python xifaims_analysis.py parameters/faims_small.yaml data/combined_8PMLunique_4PMLS_nonu.csv
python xifaims_analysis.py parameters/faims_structure.yaml data/combined_8PMLunique_4PMLS_nonu.csv
python xifaims_analysis.py parameters/faims_all.yaml data/combined_8PMLunique_4PMLS_nonu.csv